export const THEME = {
  DIGIT: 'DIGIT',
  MAIN_OP: 'MAIN_OP',
  SECONDARY_OP: 'SECONDARY_OP',
}

export const COMMAND = {
  DIGIT: 'DIGIT',
  RESET: 'RESET',
  TOGGLE_SIGN: 'TOGGLE_SIGN',
  PERCENTAGE: 'PERCENTAGE',
  DIVISION: 'DIVISION',
  MULTIPLICATION: 'MULTIPLICATION',
  SUBTRACTION: 'SUBTRACTION',
  ADDITION: 'ADDITION',
  EQUAL: 'EQUAL',
  RATIONAL: 'RATIONAL'
}